import { QueryInterface } from "sequelize";
import { v4 as uuidv4 } from "uuid";

export default {
  async up(queryInterface: QueryInterface) {
    const now = new Date();
    const userId = await queryInterface.sequelize.query(
      `SELECT id, fullname FROM users;`
    );

    const userIdMap: { [key: string]: string } = {};
    userId[0].forEach((user: any, index: number) => {
      userIdMap[user.fullname] = user.id;
    });

    const courseId = await queryInterface.sequelize.query(
      `SELECT id, title FROM courses;`
    );

    const courseIdMap: { [key: string]: {id: string, title:   string} } = {};
    courseId[0].forEach((course: any, index: number) => {
      courseIdMap[course.title] = {id: course.id, title: course.title};
    });

    const tryoutId = await queryInterface.sequelize.query(
      `SELECT id, title FROM tryout_sections;`
    );

    const tryoutIdMap: { [key: string]: {id: string, title: string }} = {};
    tryoutId[0].forEach((tryout: any, index: number) => {
      tryoutIdMap[tryout.title] = {id: tryout.id, title: tryout.title};
    });

    const exams = [
      {
        id: uuidv4(),
        userId: userIdMap["Sigit Sasongko"],
        tag: null,
        active: 1,
        data: JSON.stringify({
          scores: 0,
          status: "submitted",
          endTime: "2025-05-04T11:37:57.095Z",
          duration: 3600000,
          platform: "website",
          questions: [
            {
              id: "704f3f84-8c52-4627-a211-e0499f7e1bde",
              score: 0,
              answer: null,
              imageType: "asset",
              examAnswer: null,
              scrambledLabel: [
                { label: "a", examLabel: "a" },
                { label: "b", examLabel: "b" },
                { label: "d", examLabel: "c" },
                { label: "c", examLabel: "d" },
              ],
              tryoutSections: [{ id: "3c91e9f7-f803-426c-8966-4fd4dd812286" }],
            },
            {
              id: "aa60e833-67c1-4b8c-872a-207c434c47f5",
              score: 0,
              answer: null,
              imageType: "asset",
              examAnswer: null,
              scrambledLabel: [
                { label: "c", examLabel: "a" },
                { label: "b", examLabel: "b" },
                { label: "a", examLabel: "c" },
                { label: "d", examLabel: "d" },
              ],
              tryoutSections: [{ id: "3c91e9f7-f803-426c-8966-4fd4dd812286" }],
            },
            {
              id: "38271d80-ee91-451e-a199-7875766fbf07",
              score: 0,
              answer: null,
              imageType: "asset",
              examAnswer: null,
              scrambledLabel: [
                { label: "d", examLabel: "a" },
                { label: "c", examLabel: "b" },
                { label: "b", examLabel: "c" },
                { label: "a", examLabel: "d" },
              ],
              tryoutSections: [{ id: "3c91e9f7-f803-426c-8966-4fd4dd812286" }],
            },
            {
              id: "11722cb5-58de-4170-a4fb-ae5187fde0ff",
              score: 0,
              answer: null,
              imageType: "asset",
              examAnswer: null,
              scrambledLabel: [
                { label: "a", examLabel: "a" },
                { label: "b", examLabel: "b" },
                { label: "c", examLabel: "c" },
                { label: "d", examLabel: "d" },
              ],
              tryoutSections: [{ id: "3c91e9f7-f803-426c-8966-4fd4dd812286" }],
            },
            {
              id: "e3bf5034-30ac-42ff-9c9b-51ec417563b2",
              score: 0,
              answer: null,
              imageType: "asset",
              examAnswer: null,
              scrambledLabel: [
                { label: "b", examLabel: "a" },
                { label: "c", examLabel: "b" },
                { label: "d", examLabel: "c" },
                { label: "a", examLabel: "d" },
              ],
              tryoutSections: [{ id: "3c91e9f7-f803-426c-8966-4fd4dd812286" }],
            },
          ],
          startTime: "2025-05-04T10:37:57.095Z",
          tryoutSectionId: "3c91e9f7-f803-426c-8966-4fd4dd812286",
          tryoutSectionTitle: "Tryout Emotional Quotient",
        }),
        createdAt: now,
        updatedAt: now,
      },
      {
        id: uuidv4(),
        userId: userIdMap["Sigit Sasongko"],
        tag: null,
        active: 1,
        data: JSON.stringify({
          scores: 0,
          status: "submitted",
          endTime: "2025-05-04T11:43:19.154Z",
          duration: 3600000,
          platform: "website",
          questions: [
            {
              id: "704f3f84-8c52-4627-a211-e0499f7e1bde",
              score: 0,
              answer: null,
              imageType: "asset",
              examAnswer: null,
              scrambledLabel: [
                { label: "a", examLabel: "a" },
                { label: "c", examLabel: "b" },
                { label: "b", examLabel: "c" },
                { label: "d", examLabel: "d" },
              ],
              tryoutSections: [{ id: "3c91e9f7-f803-426c-8966-4fd4dd812286" }],
            },
            {
              id: "11722cb5-58de-4170-a4fb-ae5187fde0ff",
              score: 0,
              answer: null,
              imageType: "asset",
              examAnswer: null,
              scrambledLabel: [
                { label: "d", examLabel: "a" },
                { label: "a", examLabel: "b" },
                { label: "b", examLabel: "c" },
                { label: "c", examLabel: "d" },
              ],
              tryoutSections: [{ id: "3c91e9f7-f803-426c-8966-4fd4dd812286" }],
            },
            {
              id: "e3bf5034-30ac-42ff-9c9b-51ec417563b2",
              score: 0,
              answer: null,
              imageType: "asset",
              examAnswer: null,
              scrambledLabel: [
                { label: "b", examLabel: "a" },
                { label: "a", examLabel: "b" },
                { label: "d", examLabel: "c" },
                { label: "c", examLabel: "d" },
              ],
              tryoutSections: [{ id: "3c91e9f7-f803-426c-8966-4fd4dd812286" }],
            },
            {
              id: "aa60e833-67c1-4b8c-872a-207c434c47f5",
              score: 0,
              answer: null,
              imageType: "asset",
              examAnswer: null,
              scrambledLabel: [
                { label: "d", examLabel: "a" },
                { label: "b", examLabel: "b" },
                { label: "c", examLabel: "c" },
                { label: "a", examLabel: "d" },
              ],
              tryoutSections: [{ id: "3c91e9f7-f803-426c-8966-4fd4dd812286" }],
            },
            {
              id: "38271d80-ee91-451e-a199-7875766fbf07",
              score: 0,
              answer: null,
              imageType: "asset",
              examAnswer: null,
              scrambledLabel: [
                { label: "c", examLabel: "a" },
                { label: "a", examLabel: "b" },
                { label: "b", examLabel: "c" },
                { label: "d", examLabel: "d" },
              ],
              tryoutSections: [{ id: "3c91e9f7-f803-426c-8966-4fd4dd812286" }],
            },
          ],
          startTime: "2025-05-04T10:43:19.154Z",
          tryoutSectionId: "3c91e9f7-f803-426c-8966-4fd4dd812286",
          tryoutSectionTitle: "Tryout Emotional Quotient",
        }),
        createdAt: now,
        updatedAt: now,
      },
      {
        id: uuidv4(),
        userId: userIdMap["Sigit Sasongko"],
        tag: null,
        active: 1,
        data: JSON.stringify({
          scores: 0,
          status: "submitted",
          endTime: "2025-05-04T09:36:54.676Z",
          duration: 3600000,
          platform: "website",
          questions: [
            {
              id: "e3bf5034-30ac-42ff-9c9b-51ec417563b2",
              score: 0,
              answer: "a",
              imageType: "asset",
              examAnswer: "c",
              scrambledLabel: [
                { label: "b", examLabel: "a" },
                { label: "c", examLabel: "b" },
                { label: "a", examLabel: "c" },
                { label: "d", examLabel: "d" },
              ],
              tryoutSections: [{ id: "3c91e9f7-f803-426c-8966-4fd4dd812286" }],
            },
            {
              id: "aa60e833-67c1-4b8c-872a-207c434c47f5",
              score: 0,
              answer: null,
              imageType: "asset",
              examAnswer: null,
              scrambledLabel: [
                { label: "b", examLabel: "a" },
                { label: "d", examLabel: "b" },
                { label: "c", examLabel: "c" },
                { label: "a", examLabel: "d" },
              ],
              tryoutSections: [{ id: "3c91e9f7-f803-426c-8966-4fd4dd812286" }],
            },
            {
              id: "704f3f84-8c52-4627-a211-e0499f7e1bde",
              score: 0,
              answer: null,
              imageType: "asset",
              examAnswer: null,
              scrambledLabel: [
                { label: "b", examLabel: "a" },
                { label: "a", examLabel: "b" },
                { label: "d", examLabel: "c" },
                { label: "c", examLabel: "d" },
              ],
              tryoutSections: [{ id: "3c91e9f7-f803-426c-8966-4fd4dd812286" }],
            },
            {
              id: "38271d80-ee91-451e-a199-7875766fbf07",
              score: 0,
              answer: null,
              imageType: "asset",
              examAnswer: null,
              scrambledLabel: [
                { label: "b", examLabel: "a" },
                { label: "d", examLabel: "b" },
                { label: "c", examLabel: "c" },
                { label: "a", examLabel: "d" },
              ],
              tryoutSections: [{ id: "3c91e9f7-f803-426c-8966-4fd4dd812286" }],
            },
            {
              id: "11722cb5-58de-4170-a4fb-ae5187fde0ff",
              score: 0,
              answer: null,
              imageType: "asset",
              examAnswer: null,
              scrambledLabel: [
                { label: "a", examLabel: "a" },
                { label: "c", examLabel: "b" },
                { label: "d", examLabel: "c" },
                { label: "b", examLabel: "d" },
              ],
              tryoutSections: [{ id: "3c91e9f7-f803-426c-8966-4fd4dd812286" }],
            },
          ],
          startTime: "2025-05-04T08:36:54.676Z",
          tryoutSectionId: "3c91e9f7-f803-426c-8966-4fd4dd812286",
          tryoutSectionTitle: "Tryout Emotional Quotient",
        }),
        createdAt: now,
        updatedAt: now,
      },
      {
        id: uuidv4(),
        userId: userIdMap["Bobby Dharma"],
        tag: null,
        active: 1,
        data: JSON.stringify({
          scores: 0,
          status: "submitted",
          endTime: "2025-05-04T11:40:19.952Z",
          duration: 3600000,
          platform: "website",
          questions: [
            {
              id: "38271d80-ee91-451e-a199-7875766fbf07",
              score: 0,
              answer: null,
              imageType: "asset",
              examAnswer: null,
              scrambledLabel: [
                { label: "d", examLabel: "a" },
                { label: "b", examLabel: "b" },
                { label: "c", examLabel: "c" },
                { label: "a", examLabel: "d" },
              ],
              tryoutSections: [{ id: "3c91e9f7-f803-426c-8966-4fd4dd812286" }],
            },
            {
              id: "aa60e833-67c1-4b8c-872a-207c434c47f5",
              score: 0,
              answer: null,
              imageType: "asset",
              examAnswer: null,
              scrambledLabel: [
                { label: "b", examLabel: "a" },
                { label: "c", examLabel: "b" },
                { label: "d", examLabel: "c" },
                { label: "a", examLabel: "d" },
              ],
              tryoutSections: [{ id: "3c91e9f7-f803-426c-8966-4fd4dd812286" }],
            },
            {
              id: "11722cb5-58de-4170-a4fb-ae5187fde0ff",
              score: 0,
              answer: null,
              imageType: "asset",
              examAnswer: null,
              scrambledLabel: [
                { label: "b", examLabel: "a" },
                { label: "c", examLabel: "b" },
                { label: "d", examLabel: "c" },
                { label: "a", examLabel: "d" },
              ],
              tryoutSections: [{ id: "3c91e9f7-f803-426c-8966-4fd4dd812286" }],
            },
            {
              id: "e3bf5034-30ac-42ff-9c9b-51ec417563b2",
              score: 0,
              answer: null,
              imageType: "asset",
              examAnswer: null,
              scrambledLabel: [
                { label: "c", examLabel: "a" },
                { label: "a", examLabel: "b" },
                { label: "b", examLabel: "c" },
                { label: "d", examLabel: "d" },
              ],
              tryoutSections: [{ id: "3c91e9f7-f803-426c-8966-4fd4dd812286" }],
            },
            {
              id: "704f3f84-8c52-4627-a211-e0499f7e1bde",
              score: 0,
              answer: null,
              imageType: "asset",
              examAnswer: null,
              scrambledLabel: [
                { label: "a", examLabel: "a" },
                { label: "b", examLabel: "b" },
                { label: "d", examLabel: "c" },
                { label: "c", examLabel: "d" },
              ],
              tryoutSections: [{ id: "3c91e9f7-f803-426c-8966-4fd4dd812286" }],
            },
          ],
          startTime: "2025-05-04T10:40:19.952Z",
          tryoutSectionId: tryoutIdMap["Tryout Corporate Champion Mentality"].id,
          tryoutSectionTitle: tryoutIdMap["Tryout Corporate Champion Mentality"].title,
        }),
        createdAt: now,
        updatedAt: now,
      },
      {
        id: uuidv4(),
        userId: userIdMap["Bobby Dharma"],
        tag: null,
        active: 1,
        data: JSON.stringify({
          scores: 0,
          status: "submitted",
          endTime: "2025-05-04T11:41:57.125Z",
          duration: 3700000,
          platform: "website",
          questions: [
            {
              id: "11722cb5-58de-4170-a4fb-ae5187fde0ff",
              score: 0,
              answer: null,
              imageType: "asset",
              examAnswer: null,
              scrambledLabel: [
                { label: "d", examLabel: "a" },
                { label: "c", examLabel: "b" },
                { label: "b", examLabel: "c" },
                { label: "a", examLabel: "d" },
              ],
              tryoutSections: [{ id: "3c91e9f7-f803-426c-8966-4fd4dd812286" }],
            },
            {
              id: "aa60e833-67c1-4b8c-872a-207c434c47f5",
              score: 0,
              answer: null,
              imageType: "asset",
              examAnswer: null,
              scrambledLabel: [
                { label: "d", examLabel: "a" },
                { label: "b", examLabel: "b" },
                { label: "a", examLabel: "c" },
                { label: "c", examLabel: "d" },
              ],
              tryoutSections: [{ id: "3c91e9f7-f803-426c-8966-4fd4dd812286" }],
            },
            {
              id: "e3bf5034-30ac-42ff-9c9b-51ec417563b2",
              score: 0,
              answer: null,
              imageType: "asset",
              examAnswer: null,
              scrambledLabel: [
                { label: "a", examLabel: "a" },
                { label: "b", examLabel: "b" },
                { label: "c", examLabel: "c" },
                { label: "d", examLabel: "d" },
              ],
              tryoutSections: [{ id: "3c91e9f7-f803-426c-8966-4fd4dd812286" }],
            },
            {
              id: "38271d80-ee91-451e-a199-7875766fbf07",
              score: 0,
              answer: null,
              imageType: "asset",
              examAnswer: null,
              scrambledLabel: [
                { label: "a", examLabel: "a" },
                { label: "b", examLabel: "b" },
                { label: "d", examLabel: "c" },
                { label: "c", examLabel: "d" },
              ],
              tryoutSections: [{ id: "3c91e9f7-f803-426c-8966-4fd4dd812286" }],
            },
            {
              id: "704f3f84-8c52-4627-a211-e0499f7e1bde",
              score: 0,
              answer: null,
              imageType: "asset",
              examAnswer: null,
              scrambledLabel: [
                { label: "d", examLabel: "a" },
                { label: "b", examLabel: "b" },
                { label: "c", examLabel: "c" },
                { label: "a", examLabel: "d" },
              ],
              tryoutSections: [{ id: "3c91e9f7-f803-426c-8966-4fd4dd812286" }],
            },
          ],
          startTime: "2025-05-04T10:41:57.125Z",
          tryoutSectionId: tryoutIdMap["ISO-27001:2022 - Phincon"].id,
          tryoutSectionTitle: tryoutIdMap["ISO-27001:2022 - Phincon"].title,
        }),
        createdAt: now,
        updatedAt: now,
      },
      {
        id: uuidv4(),
        userId: userIdMap["Bobby Dharma"],
        tag: null,
        active: 1,
        data: JSON.stringify({
          scores: 100,
          status: "submitted",
          endTime: "2025-05-03T16:36:56.968Z",
          duration: 3650000,
          platform: "website",
          questions: [
            {
              id: "332f99e8-daf4-4aa3-82e2-939fde33e3de",
              score: 1,
              answer: "b",
              imageType: "asset",
              examAnswer: "b",
              scrambledLabel: [
                { label: "a", examLabel: "a" },
                { label: "b", examLabel: "b" },
                { label: "c", examLabel: "c" },
                { label: "d", examLabel: "d" },
              ],
              tryoutSections: [{ id: "fb230eab-487b-4726-a01f-1caa056cbdee" }],
            },
            {
              id: "b44bbadb-089f-4053-a311-7b0d26a33145",
              score: 1,
              answer: "b",
              imageType: "asset",
              examAnswer: "a",
              scrambledLabel: [
                { label: "b", examLabel: "a" },
                { label: "d", examLabel: "b" },
                { label: "c", examLabel: "c" },
                { label: "a", examLabel: "d" },
              ],
              tryoutSections: [{ id: "fb230eab-487b-4726-a01f-1caa056cbdee" }],
            },
            {
              id: "d4261e64-c229-48e3-b646-db9acc50d499",
              score: 1,
              answer: "c",
              imageType: "asset",
              examAnswer: "b",
              scrambledLabel: [
                { label: "a", examLabel: "a" },
                { label: "c", examLabel: "b" },
                { label: "b", examLabel: "c" },
                { label: "d", examLabel: "d" },
              ],
              tryoutSections: [{ id: "fb230eab-487b-4726-a01f-1caa056cbdee" }],
            },
            {
              id: "90a18775-6b82-4cad-9e7a-ae42ae205b26",
              score: 1,
              answer: "c",
              imageType: "asset",
              examAnswer: "d",
              scrambledLabel: [
                { label: "d", examLabel: "a" },
                { label: "a", examLabel: "b" },
                { label: "b", examLabel: "c" },
                { label: "c", examLabel: "d" },
              ],
              tryoutSections: [{ id: "fb230eab-487b-4726-a01f-1caa056cbdee" }],
            },
            {
              id: "852b4741-0022-4fb3-8296-f429001068b8",
              score: 1,
              answer: "a",
              imageType: "asset",
              examAnswer: "c",
              scrambledLabel: [
                { label: "d", examLabel: "a" },
                { label: "c", examLabel: "b" },
                { label: "a", examLabel: "c" },
                { label: "b", examLabel: "d" },
              ],
              tryoutSections: [{ id: "fb230eab-487b-4726-a01f-1caa056cbdee" }],
            },
          ],
          startTime: "2025-05-03T15:36:56.968Z",
          courseId: courseIdMap["Security System Standard"].id,
          courseTitle: courseIdMap["Security System Standard"].title,
        }),
        createdAt: now,
        updatedAt: now,
      },
      {
        id: uuidv4(),
        userId: userIdMap["Bobby Dharma"],
        tag: null,
        active: 1,
        data: JSON.stringify({
          scores: 0,
          status: "submitted",
          endTime: "2025-05-04T09:37:05.719Z",
          duration: 3800000,
          platform: "website",
          questions: [
            {
              id: "51a811ca-30de-42b8-ad78-c75db29aa4b5",
              score: 0,
              answer: "b",
              imageType: "asset",
              examAnswer: "a",
              scrambledLabel: [
                { label: "b", examLabel: "a" },
                { label: "c", examLabel: "b" },
                { label: "d", examLabel: "c" },
                { label: "a", examLabel: "d" },
              ],
              tryoutSections: [{ id: "d506c296-a141-4780-82b1-a70e9dc4c9ef" }],
            },
            {
              id: "60d5aa19-81fd-4332-be8e-5dd7b0b06ce7",
              score: 0,
              answer: "c",
              imageType: "asset",
              examAnswer: "b",
              scrambledLabel: [
                { label: "a", examLabel: "a" },
                { label: "c", examLabel: "b" },
                { label: "b", examLabel: "c" },
                { label: "d", examLabel: "d" },
              ],
              tryoutSections: [{ id: "d506c296-a141-4780-82b1-a70e9dc4c9ef" }],
            },
            {
              id: "2ac8584b-10d6-4ff4-b561-c6366968aa49",
              score: 0,
              answer: null,
              imageType: "asset",
              examAnswer: null,
              scrambledLabel: [
                { label: "a", examLabel: "a" },
                { label: "c", examLabel: "b" },
                { label: "b", examLabel: "c" },
                { label: "d", examLabel: "d" },
              ],
              tryoutSections: [{ id: "d506c296-a141-4780-82b1-a70e9dc4c9ef" }],
            },
            {
              id: "d506e622-8f34-4460-baf0-3e46e8c9f99d",
              score: 0,
              answer: null,
              imageType: "asset",
              examAnswer: null,
              scrambledLabel: [
                { label: "c", examLabel: "a" },
                { label: "a", examLabel: "b" },
                { label: "d", examLabel: "c" },
                { label: "b", examLabel: "d" },
              ],
              tryoutSections: [{ id: "d506c296-a141-4780-82b1-a70e9dc4c9ef" }],
            },
            {
              id: "f1e37df6-6bc8-4e0f-b14a-292a83a59299",
              score: 0,
              answer: null,
              imageType: "asset",
              examAnswer: null,
              scrambledLabel: [
                { label: "a", examLabel: "a" },
                { label: "c", examLabel: "b" },
                { label: "d", examLabel: "c" },
                { label: "b", examLabel: "d" },
              ],
              tryoutSections: [{ id: "d506c296-a141-4780-82b1-a70e9dc4c9ef" }],
            },
          ],
          startTime: "2025-05-04T08:37:05.719Z",
          courseId: courseIdMap["Secure System Development Lifecycle"].id,
          courseTitle: courseIdMap["Secure System Development Lifecycle"].title,
        }),
        createdAt: now,
        updatedAt: now,
      },
    ];

    await queryInterface.bulkInsert("exams", exams, {});
  },

  async down(queryInterface: QueryInterface) {
    await queryInterface.bulkDelete("exams", {});
  },
};
